### ISSUE TITLE
[Docs] 템플릿 설정

### ISSUE THREAD

**Issue by acycoco** [AhnSeene/find-my-meme-backend#1]
### 💼 작업 설명
템플릿 설정했습니다.

### ✅ To-do

- [x] 버그 이슈 템플릿
- [x] feature 이슈 템플릿
- [x] pull request 템플릿
- [x] git commit 템플릿
