### ISSUE TITLE
[Chore] 테스트 application.yml생성 

### ISSUE THREAD

**Issue by acycoco** [AhnSeene/find-my-meme-backend#12]
### 💼 작업 설명
테스트 application.yml생성 
h2 db로 설정
 
### ✅ To-do

- [x] 테스트 application.yml생성 
- [x] h2 build.gradle 의존성 추가
- [x] open-in-view설정, sql로깅 설정 추가
