### ISSUE TITLE
[Feat] Security api 권한 설정

### ISSUE THREAD

**Issue by acycoco** [AhnSeene/find-my-meme-backend#162]
### ✅ To-do

- [ ] 로그인 시에만 사용가능한 기능/아닌 기능 권한 적용
- [ ] admin api 권한 적용
- [x] 로그인 시 응답에 role도 반환
- [ ] admin유저 자동생성
