### ISSUE TITLE
[Feat] 에러 처리

### ISSUE THREAD

**Issue by acycoco** [AhnSeene/find-my-meme-backend#3]
### 💼 작업 설명
에러처리
 
### ✅ To-do

- [x] ErrorCode생성
- [x] ErrorResponse 객체 생성
- [x] 커스텀 exception 생성
- [x] 에러 핸들러 생성
