### ISSUE TITLE
[Feat] User 엔티티 및 레포지토리 생성

### ISSUE THREAD

**Issue by acycoco** [AhnSeene/find-my-meme-backend#5]
### 💼 작업 설명
User 엔티티와 레포지토리를 생성합니다. 
 
### ✅ To-do

- [x] User 엔티티 생성
- [x] User 레포지토리 생성
- [ ] User 엔티티 및 레포지토리 테스트 코드 작성
