### ISSUE TITLE
[Feat] User 프로필 이미지 업데이트 구현

### ISSUE THREAD

**Issue by acycoco** [AhnSeene/find-my-meme-backend#88]
### ✅ To-do

- [x] User entity필드 추가
- [x] 회원가입시 기본이미지로 회원가입
- [x] 프로필 이미지 업데이트 구현
